#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v5
# autospec commit: c02b2fe
#
# Source0 file verified with key 0x015A268A17D55FA4 (dade.watson@gmail.com)
#
Name     : libunwind
Version  : 1.6.2
Release  : 29
URL      : https://download.savannah.gnu.org/releases/libunwind/libunwind-1.6.2.tar.gz
Source0  : https://download.savannah.gnu.org/releases/libunwind/libunwind-1.6.2.tar.gz
Source1  : https://download.savannah.gnu.org/releases/libunwind/libunwind-1.6.2.tar.gz.sig
Summary  : libunwind base library
Group    : Development/Tools
License  : MIT
Requires: libunwind-lib = %{version}-%{release}
Requires: libunwind-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libunwind
[![Build Status](https://travis-ci.org/libunwind/libunwind.svg?branch=master)](https://travis-ci.org/libunwind/libunwind)

%package dev
Summary: dev components for the libunwind package.
Group: Development
Requires: libunwind-lib = %{version}-%{release}
Provides: libunwind-devel = %{version}-%{release}
Requires: libunwind = %{version}-%{release}

%description dev
dev components for the libunwind package.


%package dev32
Summary: dev32 components for the libunwind package.
Group: Default
Requires: libunwind-lib32 = %{version}-%{release}
Requires: libunwind-dev = %{version}-%{release}

%description dev32
dev32 components for the libunwind package.


%package lib
Summary: lib components for the libunwind package.
Group: Libraries
Requires: libunwind-license = %{version}-%{release}

%description lib
lib components for the libunwind package.


%package lib32
Summary: lib32 components for the libunwind package.
Group: Default
Requires: libunwind-license = %{version}-%{release}

%description lib32
lib32 components for the libunwind package.


%package license
Summary: license components for the libunwind package.
Group: Default

%description license
license components for the libunwind package.


%prep
%setup -q -n libunwind-1.6.2
cd %{_builddir}/libunwind-1.6.2
pushd ..
cp -a libunwind-1.6.2 build32
popd
pushd ..
cp -a libunwind-1.6.2 buildavx2
popd

%build
## build_prepend content
CFLAGS="$CFLAGS -fcommon"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711737696
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
## build_prepend content
CFLAGS="$CFLAGS -fcommon"
## build_prepend end
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
## build_prepend content
CFLAGS="$CFLAGS -fcommon"
## build_prepend end
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711737696
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libunwind
cp %{_builddir}/libunwind-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libunwind/392f6897a0ce718eb8a6092915a520556a883d76 || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libunwind-common.h
/usr/include/libunwind-coredump.h
/usr/include/libunwind-dynamic.h
/usr/include/libunwind-ptrace.h
/usr/include/libunwind-x86.h
/usr/include/libunwind-x86_64.h
/usr/include/libunwind.h
/usr/include/unwind.h
/usr/lib64/libunwind-coredump.so
/usr/lib64/libunwind-generic.so
/usr/lib64/libunwind-ptrace.so
/usr/lib64/libunwind-setjmp.so
/usr/lib64/libunwind-x86_64.so
/usr/lib64/libunwind.so
/usr/lib64/pkgconfig/libunwind-coredump.pc
/usr/lib64/pkgconfig/libunwind-generic.pc
/usr/lib64/pkgconfig/libunwind-ptrace.pc
/usr/lib64/pkgconfig/libunwind-setjmp.pc
/usr/lib64/pkgconfig/libunwind.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libunwind-coredump.so
/usr/lib32/libunwind-generic.so
/usr/lib32/libunwind-ptrace.so
/usr/lib32/libunwind-setjmp.so
/usr/lib32/libunwind-x86.so
/usr/lib32/libunwind.so
/usr/lib32/pkgconfig/32libunwind-coredump.pc
/usr/lib32/pkgconfig/32libunwind-generic.pc
/usr/lib32/pkgconfig/32libunwind-ptrace.pc
/usr/lib32/pkgconfig/32libunwind-setjmp.pc
/usr/lib32/pkgconfig/32libunwind.pc
/usr/lib32/pkgconfig/libunwind-coredump.pc
/usr/lib32/pkgconfig/libunwind-generic.pc
/usr/lib32/pkgconfig/libunwind-ptrace.pc
/usr/lib32/pkgconfig/libunwind-setjmp.pc
/usr/lib32/pkgconfig/libunwind.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libunwind-coredump.so.0.0.0
/V3/usr/lib64/libunwind-ptrace.so.0.0.0
/V3/usr/lib64/libunwind-setjmp.so.0.0.0
/V3/usr/lib64/libunwind-x86_64.so.8.0.1
/V3/usr/lib64/libunwind.so.8.0.1
/usr/lib64/libunwind-coredump.so.0
/usr/lib64/libunwind-coredump.so.0.0.0
/usr/lib64/libunwind-ptrace.so.0
/usr/lib64/libunwind-ptrace.so.0.0.0
/usr/lib64/libunwind-setjmp.so.0
/usr/lib64/libunwind-setjmp.so.0.0.0
/usr/lib64/libunwind-x86_64.so.8
/usr/lib64/libunwind-x86_64.so.8.0.1
/usr/lib64/libunwind.so.8
/usr/lib64/libunwind.so.8.0.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libunwind-coredump.so.0
/usr/lib32/libunwind-coredump.so.0.0.0
/usr/lib32/libunwind-ptrace.so.0
/usr/lib32/libunwind-ptrace.so.0.0.0
/usr/lib32/libunwind-setjmp.so.0
/usr/lib32/libunwind-setjmp.so.0.0.0
/usr/lib32/libunwind-x86.so.8
/usr/lib32/libunwind-x86.so.8.0.1
/usr/lib32/libunwind.so.8
/usr/lib32/libunwind.so.8.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libunwind/392f6897a0ce718eb8a6092915a520556a883d76
